import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "./SessionProvider"; // ⬅️ add this
import { I18nProvider } from "@/lib/i18n/provider";
import { getCurrentLocale } from "@/lib/i18n/server";
import { RoleProvider } from "@/lib/role/provider";
import { getCurrentRole } from "@/lib/role/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "V-Healthy",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#0e0f12",
  colorScheme: "dark",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getCurrentLocale();
  const role = await getCurrentRole();

  return (
    <html lang={locale} className="dark bg-background">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider locale={locale}>
          <RoleProvider role={role}>
            <AuthSessionProvider>
              {children}
            </AuthSessionProvider>
          </RoleProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
